use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Kalanhall/Specs.git'

platform :ios, '9.0'

target 'KLScaleNavigationBar_Example' do
  pod 'KLScaleNavigationBar', :path => '../'

  target 'KLScaleNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end
