use_frameworks!

platform :ios, '8.0'

target 'KLScaleNavigationBar_Example' do
  pod 'KLScaleNavigationBar', :path => '../'

  target 'KLScaleNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end
